# Generated by Django 5.0 on 2023-12-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='phone',
            field=models.IntegerField(max_length=60),
        ),
    ]
